# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='sporteventexp',
            old_name='user_id',
            new_name='athlete_id',
        ),
        migrations.AlterField(
            model_name='athletecompany',
            name='author_rep',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='athletecompany',
            name='company_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='athletecompany',
            name='credit_code',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sporteventexp',
            name='event_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, '\u7ba1\u7406\u5458'), (1, '\u4fe1\u606f\u5f55\u5165'), (2, '\u4fe1\u606f\u67e5\u8be2'), (3, '\u4fe1\u606f\u67e5\u8be2/\u4fee\u6539')], default=0),
        ),
        migrations.RemoveField(
            model_name='athletecompany',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='athletecompany',
            unique_together=set([('company_name', 'credit_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='sporteventexp',
            unique_together=set([('athlete_id', 'event_name')]),
        ),
    ]
